# Generated by Django 6.0 on 2025-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0003_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(),
        ),
    ]
